language: node_js
cache:
  directories:
    - ~/.npm
notifications:
  email: false
node_js:
  - '12'
script:
  - npm run test:prod && npm run build
after_success:
  - if [ "$TRAVIS_BRANCH" = "master" -a "$TRAVIS_PULL_REQUEST" = "false" ]; then
    npm run travis-deploy-once "npm run deploy-docs"; fi
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
