language: node_js
cache:
  directories:
    - ~/.npm
notifications:
  email: false
node_js:
  - '18'
before_script: cd votes
script:
  - npm run test-prod && npm run build
after_success:
  - if [ "$TRAVIS_BRANCH" = "master" -a "$TRAVIS_PULL_REQUEST" = "false" ]; then
    npm run travis-deploy-once "npm run publish-docs"; fi
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
