language: node_js
cache:
  directories:
    - ~/.npm
notifications:
  email: false
node_js:
  - '18'
before_script: cd votes
script:
  - yarn run lint && yarn run test && yarn run build
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
