name: Bundle-size

on:
  pull_request:
    branches:
      - main

jobs:
  size:
    runs-on: ubuntu-latest
    # compressed-size-action comments the size diff on the PR
    permissions:
      contents: read
      pull-requests: write
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1
        with:
          persist-credentials: false
      - uses: lzear/forge/actions/setup@16f6053e02114b66447b5b415d39ac2f0b0f78a0 # main
      - run: yarn workspace votes build
      - uses: preactjs/compressed-size-action@e2bfc4b346d78f9a3c7e8a2e22bcbd285a25fafa # v2.0.1
        with:
          pattern: '**/dist/**/*.{mjs,js}'
