name: "Code coverage"

on: [push]

jobs:
  release:
    name: Test coverage
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: actions/setup-node@v2-beta
        with:
          node-version: '12'
      - run: yarn install
      - run: yarn test
      - run: ./tools/codacy-cov.sh
        env:
          CODACY_PROJECT_TOKEN: ${{ secrets.CODACY_PROJECT_TOKEN }}
