name: Main

on:
  push:
  pull_request:
    branches: [main]

permissions:
  contents: read

jobs:
  ci:
    uses: lzear/forge/.github/workflows/ci.yml@fb2a4ea4b2bb49007af5e641ce86dfaf57341410 # v4.10.0
    secrets:
      CODACY_PROJECT_TOKEN: ${{ secrets.CODACY_PROJECT_TOKEN }}

  release:
    if: github.event_name == 'push'
    needs: ci
    uses: lzear/forge/.github/workflows/release.yml@fb2a4ea4b2bb49007af5e641ce86dfaf57341410 # v4.10.0
    permissions:
      contents: write
      pull-requests: write
      id-token: write
