name: Main

on:
  push:
  pull_request:
    branches: [main]

permissions:
  contents: read

jobs:
  ci:
    uses: lzear/forge/.github/workflows/ci.yml@6996b9b74d43075c98841b25c3c0962d9ed495f4 # v4.5.1
    secrets:
      CODACY_PROJECT_TOKEN: ${{ secrets.CODACY_PROJECT_TOKEN }}

  release:
    if: github.event_name == 'push'
    needs: ci
    uses: lzear/forge/.github/workflows/release.yml@6996b9b74d43075c98841b25c3c0962d9ed495f4 # v4.5.1
    permissions:
      contents: write
      pull-requests: write
      id-token: write
    with:
      snapshot-branch: beta
